### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vicentetomas** [Ponkabonk/ESP32-CAM-Demo#2]
Hello Thank you for your help.
I receive this error: On:
   opt_deviceName = doc["deviceName"].as<String>();

Error:
no match for 'operator[]' (operand types are 'ArduinoJson::StaticJsonDocument<1024u>' and 'const char [11]')

**Comment by Ponkabonk** [comment]
Update your ArduinoJson library.

Sent from my Android device.

-----Original Message-----

**Comment by Vicentetomas** [comment]
I did it and I receive same error

**Comment by Ponkabonk** [comment]
Make sure you're running the new code and not the original version.  What you're seeing is, I'm pretty sure, being caused by some incompatibility with the ArduinoJSON library.  I can compile the code with no issue so there is something that is different between our configurations.  We just need to figure out what the difference is.

-Mike

Sent from my Android device.

-----Original Message-----

**Comment by Ponkabonk** [comment]
I just grabbed a copy from Github and it works fine for me.  The line in question should be:
opt_deviceName = doc["deviceName"].as\<String\>();

I think I see what's happening in these posts.  The editor is stripping out what looks like HTML.  I escaped the line above to be able to show the correct code.  I suspect that your line is correct but just not showing in this editor.

1. Are you using an ESP32-Cam?
2. What version of ArduinoJSON are you using?

**Comment by Vicentetomas** [comment]
Sorry I couldn't work with it again since yesterday. I deleted all the arduino.json files  and installed it again. Now it can be recorded into the the esp32cam
But, How should it work?. 
I only see this text in the website: "I wanna hang a map of the world in my house. Then I'm gonna put pins into all the locations that I've traveled to. But first, I'm gonna have to travel to the top two corners of the map so it won't fall down" and the  file config.txt in the SD. Nothing else.

The espcam that i'm using is 
![descarga](https://user-images.githubusercontent.com/51045691/59249058-407a9f00-8c24-11e9-9667-f7ce17ba6616.jpg)

Thank very much for your time!.

**Comment by Ponkabonk** [comment]
It looks like you got your IDE fixed and everything is working.  Congratulations!  This isn't intended to be a tutorial but rather assumes you already understand the basics of making a Web server with the ESP32.  Since you're having trouble figuring out from the code how to interact with this demo, I suggest looking at one of the many excellent tutorials easily found on how to make a Web server using the ESP32 or the ESP8266.
